schema: "classroom50/repo-config/v1"
classroom: "pm-class"
assignment: "css-cv"
owner:
  username: "AlekPenny"
  id: 168767415
  accepted_at: "2026-09-08T16:04:48Z"
source:
  owner: "CSCI4300-Web-Programming"
  owner_id: 212650580
  repo: "css-cv-template"
  branch: "main"
